if: branch = test OR tag is present

language: java
jdk:
  - oraclejdk11

sudo: required
services:
  - docker

install:
  - ./gradlew build -x check --scan --no-daemon

jobs:
  include:
    #- stage: test
    #  env: [ NAME=core ]
    #  script: ./gradlew testcontainers:check javadoc --scan --no-daemon

    #- stage: test
    #  env: [ NAME=core ]
    #  jdk: openjdk11
    #  script: ./gradlew testcontainers:check --scan --no-daemon

    - stage: test
      env: [ NAME=mongodb-test ]
      script: ./gradlew mongodb:check --scan --no-daemon

    - stage: test
      env: [ NAME=mongodb-test ]
      jdk: openjdk12
      script: ./gradlew mongodb:check --scan --no-daemon

      #- env: [ NAME=selenium ]
    #  script: ./gradlew selenium:check --scan --no-daemon

    #- env: [ NAME=modules ]
    #  script: ./gradlew check -x testcontainers:check -x selenium:check -x jdbc-test:check --scan --no-daemon

    #- env: [ NAME=jdbc ]
    #  script: ./gradlew jdbc-test:check --scan --no-daemon

    #- env: [ NAME=examples ]
    #  script: cd examples && ../gradlew check --no-daemon

    # Run Docker-in-Docker tests inside Alpine
    #- env: [ NAME="docker-in-alpine-docker" ]
    #  script:
    #    - |
    #            DOCKER_HOST=unix:///var/run/docker.sock DOCKER_TLS_VERIFY= docker run -t --rm \
    #            -v "$HOME/.gradle":/root/.gradle/ \
    #            -v /var/run/docker.sock:/var/run/docker.sock \
    #            -v "$(pwd)":"$(pwd)" \
    #            -w "$(pwd)" \
    #            openjdk:8-jdk-alpine \
    #            ./gradlew --no-daemon testcontainers:test --tests '*GenericContainerRuleTest' --scan

    - stage: dependent-test
      env: [ NAME=docker-in-mongodb ]
      script:
          - |
              DOCKER_HOST=unix:///var/run/docker.sock DOCKER_TLS_VERIFY= docker run -t --rm \
              -v "$HOME/.gradle":/root/.gradle/ \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v "$(pwd)":"$(pwd)" \
              -w "$(pwd)" \
              openjdk:8-jdk-alpine \
              ./gradlew mongodb:integrationTest --scan --no-daemon

    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      deploy:
        provider: script
        script: ./gradlew -Pversion=$TRAVIS_TAG release --scan --no-daemon
        on:
          tags: true
          branch: master
